name: Deploy Infrastructure
on:
  workflow_dispatch:
    inputs:
      terraform_action:
        type: choice
        description: 'Select the Terraform action to perform'
        required: true
        options:
          - plan
          - apply
          - destroy
        default: plan
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  pull-requests: read

jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-north-1
          role-to-assume: arn:aws:iam::600627332632:role/GithubActions
          role-session-name: github-actions
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      
      - name: Terraform init
        run: terraform init
      
      - name: Terraform validate
        run: terraform validate
      
      # - name: Terraform format check
      #   run: terraform fmt -check
      
      - name: Terraform plan (on push)
        if: ${{ github.event_name == 'push' }}
        run: terraform plan
      
      - name: Terraform plan (manual dispatch)
        if: ${{ github.event.inputs.terraform_action == 'plan' || github.event.inputs.terraform_action == '' }}
        run: terraform plan 
      
      - name: Terraform apply
        if: ${{ github.event.inputs.terraform_action == 'apply' }}
        run: terraform apply -auto-approve 
      
      - name: Terraform destroy
        if: ${{ github.event.inputs.terraform_action == 'destroy' }}
        run: terraform destroy -auto-approve
